import { PurchaseRequisitionRecord, UserDepartmentMappingRecord, SpendRecord } from '../../../core/types/spend';

export function generateSampleUserDepartmentMappings(): UserDepartmentMappingRecord[] {
  return [
    {
      id: 'usr-map-1',
      username: 'carren.mokalu',
      fullName: 'Carren Mokalu',
      department: 'Legal & Corporate Governance',
      costCenter: '0003',
      hospitalUnitCode: '0000',
      hospitalName: 'Siloam Hospitals Head Office CGP',
      email: 'carren.mokalu@siloamhospitals.com',
      title: 'Legal Counsel & Compliance Specialist',
      isActive: true,
    },
    {
      id: 'usr-map-2',
      username: 'angelina.wijaya',
      fullName: 'Angelina Wijaya',
      department: 'Strategy & Commercial',
      costCenter: '0013',
      hospitalUnitCode: '0000',
      hospitalName: 'Siloam Hospitals Head Office CGP',
      email: 'angelina.wijaya@siloamhospitals.com',
      title: 'Commercial Strategy Manager',
      isActive: true,
    },
    {
      id: 'usr-map-3',
      username: 'florencia.elnidwya',
      fullName: 'Florencia Elnidwya',
      department: 'Group Procurement (CGP)',
      costCenter: '0015',
      hospitalUnitCode: '0000',
      hospitalName: 'Siloam Hospitals Head Office CGP',
      email: 'florencia.elnidwya@siloamhospitals.com',
      title: 'Senior Category Buyer',
      isActive: true,
    },
    {
      id: 'usr-map-4',
      username: 'digitalbusiness',
      fullName: 'Digital Business Transformation',
      department: 'Strategy & Commercial (Digital)',
      costCenter: '0013',
      hospitalUnitCode: '0000',
      hospitalName: 'Siloam Hospitals Head Office CGP',
      email: 'digital.business@siloamhospitals.com',
      title: 'Product Owner - Digital Transformation',
      isActive: true,
    },
    {
      id: 'usr-map-5',
      username: 'dr.hendra.setiawan',
      fullName: 'dr. Hendra Setiawan, Sp.An',
      department: 'Medical Services & ICU',
      costCenter: '1001',
      hospitalUnitCode: '0001',
      hospitalName: 'Siloam Hospitals Lippo Village',
      email: 'hendra.setiawan@siloamhospitals.com',
      title: 'Head of Critical Care & Anaesthesia',
      isActive: true,
    },
    {
      id: 'usr-map-6',
      username: 'apt.maya.pratiwi',
      fullName: 'apt. Maya Pratiwi, S.Farm',
      department: 'Pharmacy & Therapeutics',
      costCenter: '1002',
      hospitalUnitCode: '0001',
      hospitalName: 'Siloam Hospitals Lippo Village',
      email: 'maya.pratiwi@siloamhospitals.com',
      title: 'Head of Hospital Pharmacy',
      isActive: true,
    },
    {
      id: 'usr-map-7',
      username: 'budi.santoso',
      fullName: 'Budi Santoso, S.T.',
      department: 'IT & Biomedical Engineering',
      costCenter: '1005',
      hospitalUnitCode: '0002',
      hospitalName: 'Siloam Hospitals Kebon Jeruk',
      email: 'budi.santoso@siloamhospitals.com',
      title: 'Biomedical Operations Lead',
      isActive: true,
    },
    {
      id: 'usr-map-8',
      username: 'dr.rachel.ong',
      fullName: 'dr. Rachel Ong, Sp.Onk.Rad',
      department: 'Oncology Division',
      costCenter: '1008',
      hospitalUnitCode: '0003',
      hospitalName: 'MRCCC Siloam Hospitals Semanggi',
      email: 'rachel.ong@mrccc.siloamhospitals.com',
      title: 'Chief Radiotherapy Specialist',
      isActive: true,
    },
    {
      id: 'usr-map-9',
      username: 'tri.wahyuni',
      fullName: 'Tri Wahyuni',
      department: 'General Affairs & Facilities',
      costCenter: '1010',
      hospitalUnitCode: '0004',
      hospitalName: 'Siloam Hospitals Bekasi Timur',
      email: 'tri.wahyuni@siloamhospitals.com',
      title: 'Hospital Support Service Supervisor',
      isActive: true,
    },
    {
      id: 'usr-map-10',
      username: 'siti.aminah',
      fullName: 'Siti Aminah, S.Kep',
      department: 'Operating Theatre & Nursing',
      costCenter: '1012',
      hospitalUnitCode: '0008',
      hospitalName: 'Siloam Hospitals Surabaya',
      email: 'siti.aminah@siloamhospitals.com',
      title: 'OR Nurse Coordinator',
      isActive: true,
    },
    {
      id: 'usr-map-11',
      username: 'agus.hermawan',
      fullName: 'Agus Hermawan',
      department: 'Radiology & Diagnostic Imaging',
      costCenter: '1014',
      hospitalUnitCode: '0009',
      hospitalName: 'Siloam Hospitals Agora Bandung',
      email: 'agus.hermawan@siloamhospitals.com',
      title: 'Radiology Service Lead',
      isActive: true,
    },
    {
      id: 'usr-map-12',
      username: 'kartika.dewi',
      fullName: 'dr. Kartika Dewi, Sp.PK',
      department: 'Central Laboratory & Pathology',
      costCenter: '1018',
      hospitalUnitCode: '0011',
      hospitalName: 'Siloam Hospitals Dhirga Surya Medan',
      email: 'kartika.dewi@siloamhospitals.com',
      title: 'Head of Clinical Pathology',
      isActive: true,
    },
    {
      id: 'usr-map-13',
      username: 'i.wayan.suwena',
      fullName: 'I Wayan Suwena',
      department: 'Facilities & Hospitality',
      costCenter: '1020',
      hospitalUnitCode: '0013',
      hospitalName: 'Siloam Hospitals Denpasar Bali',
      email: 'wayan.suwena@siloamhospitals.com',
      title: 'Facilities Manager',
      isActive: true,
    },
    {
      id: 'usr-map-14',
      username: 'muhammad.hasan',
      fullName: 'Muhammad Hasan, S.T.',
      department: 'ICU & Medical Devices Maintenance',
      costCenter: '1025',
      hospitalUnitCode: '0014',
      hospitalName: 'Siloam Hospitals Makassar',
      email: 'muhammad.hasan@siloamhospitals.com',
      title: 'Medical Devices Support Supervisor',
      isActive: true,
    },
    {
      id: 'usr-map-15',
      username: 'dedy.kurniawan',
      fullName: 'dr. Dedy Kurniawan, Sp.B',
      department: 'Emergency & Trauma Center',
      costCenter: '1028',
      hospitalUnitCode: '0015',
      hospitalName: 'Siloam Hospitals Balikpapan',
      email: 'dedy.kurniawan@siloamhospitals.com',
      title: 'Emergency Department Head',
      isActive: true,
    },
    {
      id: 'usr-map-16',
      username: 'nadia.frontoffice',
      fullName: 'Nadia Safitri, S.I.Kom',
      department: 'Front Office',
      costCenter: '1035',
      hospitalUnitCode: '0001',
      hospitalName: 'Siloam Hospitals Lippo Village',
      email: 'nadia.safitri@siloamhospitals.com',
      title: 'Head of Front Office & Reception',
      isActive: true,
    },
    {
      id: 'usr-map-17',
      username: 'bambang.fmsga',
      fullName: 'Bambang Supriyanto, S.T.',
      department: 'Facility Management Service & General Affair (FMS - GA)',
      costCenter: '5000',
      hospitalUnitCode: '0002',
      hospitalName: 'Siloam Hospitals Kebon Jeruk',
      email: 'bambang.supriyanto@siloamhospitals.com',
      title: 'FMS & General Affairs Supervisor',
      isActive: true,
    },
  ];
}

/**
 * Generates PR records paired directly with existing POs (SpendRecords)
 */
export function generateSamplePrRecords(spendRecords: SpendRecord[] = []): PurchaseRequisitionRecord[] {
  const users = generateSampleUserDepartmentMappings();
  const prs: PurchaseRequisitionRecord[] = [];

  // 1. Exact samples matching screenshot for Unit 0000 & 1001
  const screenshotPrs = [
    {
      unit: '0000',
      prId: 'pr-0000-26-01-00001',
      subject: 'Professional fees Nindyo 2026',
      categoryType: 'professional fees (consultant)',
      requester: 'carren.mokalu',
      costCenter: '0003',
      description: 'legal',
      erpId: 'PO-0000-260100006',
      amount: 199800000,
    },
    {
      unit: '0000',
      prId: 'pr-0000-26-01-00002',
      subject: 'Ecat: Shutterstock dan iStock Desember 2025',
      categoryType: 'other opex',
      requester: 'angelina.wijaya',
      costCenter: '0013',
      description: 'strategy and commercial',
      erpId: 'PO-0000-260100001,PO-0000-260100002',
      amount: 3501708,
    },
    {
      unit: '0000',
      prId: 'pr-0000-26-01-00003',
      subject: 'Ecat: Monthly Subscription Cursor AI',
      categoryType: 'contract service / repair & maintenance',
      requester: 'florencia.elnidwya',
      costCenter: '0015',
      description: 'procurement',
      erpId: 'PO-0000-260100003',
      amount: 1250625,
    },
    {
      unit: '0000',
      prId: 'pr-0000-26-01-00004',
      subject: 'HBI-24-010 - Ultra Plan (DB Jan Subscription Ultra 2026)',
      categoryType: 'other opex',
      requester: 'digitalbusiness',
      costCenter: '0013',
      description: 'strategy and commercial',
      erpId: 'PO-0000-260100004',
      amount: 18880101,
    },
    {
      unit: '0000',
      prId: 'pr-0000-26-01-00005',
      subject: 'HBI-24-010 - Ultra Plan (DB Feb Subscription Ultra 2026)',
      categoryType: 'other opex',
      requester: 'digitalbusiness',
      costCenter: '0013',
      description: 'strategy and commercial',
      erpId: 'PO-0000-260100005',
      amount: 18880101,
    },
    {
      unit: '0000',
      prId: 'pr-0000-26-01-00006',
      subject: 'Ecat: Kartu Nama - Sales Team (new logo)',
      categoryType: 'other opex',
      requester: 'thenia.thenia',
      costCenter: '0013',
      description: 'strategy and commercial',
      erpId: 'PO-0000-260100009',
      amount: 4329000,
    },
    {
      unit: '0000',
      prId: 'pr-0000-26-01-00007',
      subject: 'Ecat: CAP STEMPEL - NEW LOGO SILOAM - NEW LOGO SILOAM',
      categoryType: 'other opex',
      requester: 'thenia.thenia',
      costCenter: '0013',
      description: 'strategy and commercial',
      erpId: 'PO-0000-260100025',
      amount: 111000,
    },
    {
      unit: '0000',
      prId: 'pr-0000-26-01-00008',
      subject: 'Ecat: Emplifi - Social media analytic tools',
      categoryType: 'other opex',
      requester: 'hervira.veronica',
      costCenter: '0013',
      description: 'strategy and commercial',
      erpId: 'PO-0000-260100016',
      amount: 251775000,
    },
    {
      unit: '0000',
      prId: 'pr-0000-26-01-00009',
      subject: 'Ecat: Tiktok Management 2026',
      categoryType: 'other opex',
      requester: 'hervira.veronica',
      costCenter: '0013',
      description: 'strategy and commercial',
      erpId: 'PO-0000-260100044',
      amount: 522144000,
    },
    {
      unit: '0000',
      prId: 'pr-0000-26-01-00012',
      subject: 'Ecat: Insider Service Fee Q1 (Jan-Mar 2026)',
      categoryType: 'contract service / repair & maintenance',
      requester: 'iwan.kurniawan',
      costCenter: '0013',
      description: 'strategy and commercial',
      erpId: 'PO-0000-260100007',
      amount: 410550000,
    },
    {
      unit: '0000',
      prId: 'pr-0000-26-01-00013',
      subject: 'Ecat: Perpanjangan Service Qontak - Whatsapp Official',
      categoryType: 'contract service / repair & maintenance',
      requester: 'blessy.reta',
      costCenter: '0021',
      description: 'teleconsultation',
      erpId: 'PO-0000-260100014',
      amount: 256423320,
    },
    {
      unit: '0000',
      prId: 'pr-0000-26-01-00014',
      subject: 'Ecat: Sustainability Report Assurance 2025',
      categoryType: 'professional fees (consultant)',
      requester: 'marlide.banjarnahor',
      costCenter: '0097',
      description: 'corporate affairs and sustainability',
      erpId: 'PO-0000-260100030',
      amount: 133200000,
    },
    {
      unit: '0000',
      prId: 'pr-0000-26-01-00016',
      subject: 'Ecat: Microphone Yo-tronics (Pak Hendra)',
      categoryType: 'contract service / repair & maintenance',
      requester: 'theresia.suhendri',
      costCenter: '0010',
      description: 'information communication and technology',
      erpId: 'PO-0000-260100031',
      amount: 35000000,
    },
    {
      unit: '0000',
      prId: 'pr-0000-26-01-00017',
      subject: 'Ecat: Notes: cetak 4 box kartu nama an Pak Charles',
      categoryType: 'other opex',
      requester: 'theresia.kayatoe',
      costCenter: '0107',
      description: 'go beyond project',
      erpId: 'PO-0000-260100010',
      amount: 288600,
    },
    {
      unit: '0000',
      prId: 'pr-0000-26-01-00020',
      subject: 'Ecat: Cetak kartu nama an Pak Sumanta',
      categoryType: 'other opex',
      requester: 'theresia.kayatoe',
      costCenter: '0013',
      description: 'strategy and commercial',
      erpId: 'PO-0000-260100013',
      amount: 288600,
    },
    {
      unit: '0000',
      prId: 'pr-0000-26-01-00021',
      subject: 'Ecat: Kartu Nama Benny Haryanto',
      categoryType: 'other opex',
      requester: 'magy.salindeho',
      costCenter: '0001',
      description: 'management',
      erpId: 'PO-0000-260300074',
      amount: 144300,
    },
    {
      unit: '0000',
      prId: 'pr-0000-26-01-00022',
      subject: 'Ecat: Kartu nama 3 box. dr. Hans Lie, dr. Irwan Gandana,',
      categoryType: 'other opex',
      requester: 'merlin.shho',
      costCenter: '0088',
      description: 'network office',
      erpId: 'PO-0000-260100017',
      amount: 216450,
    },
    {
      unit: '0000',
      prId: 'pr-0000-26-01-00023',
      subject: 'Maintenance Support Services 2026 - 2027 CMS',
      categoryType: 'professional fees (consultant)',
      requester: 'carren.mokalu',
      costCenter: '0003',
      description: 'legal',
      erpId: 'PO-0000-260100015',
      amount: 360000000,
    },
    {
      unit: '0000',
      prId: 'pr-0000-26-01-00025',
      subject: 'SE005 - Ultra Plan PE NTMY (Jan-Feb 2026)',
      categoryType: 'other opex',
      requester: 'christine.yana',
      costCenter: '0113',
      description: '(ho only) patient experience',
      erpId: 'PO-0000-260100028',
      amount: 18880101,
    },
    {
      unit: '0000',
      prId: 'pr-0000-26-01-00027',
      subject: 'Ecat: Kartu nama untuk dr. Grace 2 pax dan Bu Yanti 2 pa',
      categoryType: 'other opex',
      requester: 'theresia.giavany',
      costCenter: '0006',
      description: 'medical',
      erpId: 'PO-0000-260100026',
      amount: 288600,
    },
    {
      unit: '0000',
      prId: 'pr-0000-26-01-00030',
      subject: 'Ecat: Maintenance Support Service [DDG] Billed Quarterly',
      categoryType: 'contract service / repair & maintenance',
      requester: 'theresia.giavany',
      costCenter: '0006',
      description: 'medical',
      erpId: 'PO-0000-260200037',
      amount: 375180000,
    },
    {
      unit: '0000',
      prId: 'pr-0000-26-01-00032',
      subject: 'Ecat: Paper Shredder for Secretart',
      categoryType: 'contract service / repair & maintenance',
      requester: 'magy.salindeho',
      costCenter: '0001',
      description: 'management',
      erpId: 'PO-0000-260300077',
      amount: 3185700,
    },
    {
      unit: '1001',
      prId: 'pr-1001-26-01-00001',
      subject: 'Seng Plastik Bening',
      categoryType: 'contract service / repair & maintenance',
      requester: 'jeremiah.panggabean',
      costCenter: '5000',
      description: 'facility management service & general affair',
      erpId: 'PRQ-2601-0003644',
      amount: 240000,
    },
    {
      unit: '1001',
      prId: 'pr-1001-26-01-00002',
      subject: 'Perbaikan sofa IPD Genezaret',
      categoryType: 'contract service / repair & maintenance',
      requester: 'yuni.mulyanti',
      costCenter: '5000',
      description: 'facility management service & general affair',
      erpId: 'PRQ-2601-0003646',
      amount: 1500000,
    }
  ];

  // Distinct PO IDs from spendRecords to pair with
  const distinctPoIds = Array.from(new Set(spendRecords.map(r => r.purchId).filter(Boolean)));

  // Pair screenshot PRs with first available POs or their exact erpId
  screenshotPrs.forEach((item, idx) => {
    // Include both screenshot PO identifier and the actual spendRecord PO ID so exact pairing succeeds
    const poToken = distinctPoIds[idx];
    let finalErpId = item.erpId;
    if (poToken && item.erpId && !item.erpId.includes(poToken)) {
      finalErpId = `${item.erpId},${poToken}`;
    } else if (!finalErpId && poToken) {
      finalErpId = poToken;
    }
    const isPrq = (finalErpId || '').startsWith('PRQ');

    prs.push({
      id: item.prId,
      unit: item.unit || '0000',
      purchaseReqId: item.prId,
      subject: item.subject,
      categoryType: item.categoryType,
      documentStatus: 'Approved',
      requester: item.requester,
      costCenter: item.costCenter,
      description: item.description,
      waitingTo: '',
      erpId: finalErpId,
      createdDate: '2026-01-05',
      submittedDate: '2026-01-05',
      totalAmount: item.amount,
      pairingStatus: isPrq ? 'PAIRED_PRQ' : 'PAIRED_PO',
      pairedPoCount: finalErpId.split(/[,;\s]+/).filter(Boolean).length
    });
  });

  // Pair remaining POs across other hospitals & departments
  const projectSubjectsByDept: Record<string, string[]> = {
    'Medical Services & ICU': [
      'Peremajaan Patient Monitor & Infusion Pump ICU',
      'Pengadaan Surgical Instrument Set Laparoscopy',
      'Emergency Ventilator Consumables Q1',
      'Defibrillator Upgrade & Pacing Electrodes'
    ],
    'Pharmacy & Therapeutics': [
      'Antibiotik Lini Ketiga & Formularium Khusus Q1',
      'Oncology Chemotherapy Drug Procurement Contract',
      'Pengadaan Vaksin Influenza & Hepatitis B Massal',
      'Intravenous Fluids & Nutritional Support Contract'
    ],
    'IT & Biomedical Engineering': [
      'Lisensi PACS Enterprise & Radiology Cloud Storage',
      'Upgrade Workstation Radiologi & HIS Client Terminal',
      'Pemeliharaan Preventif Mesin Anestesi & USG',
      'Perangkat Jaringan Ruang Operasi & Switch CISCO'
    ],
    'Oncology Division': [
      'Linear Accelerator (LINAC) Calibration & Quality QA',
      'PET-CT Radioisotope Tracer Gallium-68 Order',
      'Radiation Protection Lead Aprons & Thyroid Shields',
      'Brachytherapy Source Replacement & Dosimetry'
    ],
    'General Affairs & Facilities': [
      'Pembersihan Filter HEPA & HVAC Ruang Isolasi',
      'Penggantian Chiller Ruang Operasi & Rawat Inap',
      'Layanan Pengolahan Limbah Medis B3 Periode 2026',
      'Perbaikan Genset Darurat & UPS Central Rumah Sakit'
    ],
    'Central Laboratory & Pathology': [
      'Reagen Analyzer Immunoassay & Kontrol Kualitas Harian',
      'Cartridge Blood Gas Analyzer (BGA) Paket Q1',
      'Tabung Darah Vacuum & Jarum Phlebotomy Steril',
      'Reagen Pewarnaan Patologi Anatomi & Histologi'
    ],
    'Radiology & Diagnostic Imaging': [
      'Media Kontras Non-Ionik CT-Scan & MRI Paket Kuartal',
      'Penggantian Detektor Digital Radiography (DR)',
      'Film Medis & Thermal Paper USG Doppler',
      'Lead Glass Window Ruang X-Ray Diagnostic'
    ],
    'Group Procurement (CGP)': [
      'Tender Konsolidasi Sarung Tangan Steril Nitril Nasional',
      'Perjanjian Payung Suplai Spuit Disposable 3cc & 5cc',
      'Standardisasi Jarum Infus & IV Cannula Seluruh RS',
      'Kontrak Korporat Masker Bedah 3-Ply & Kasa Hidrofil'
    ]
  };

  // Assign remaining POs (up to 150 PRs)
  const remainingPoIds = distinctPoIds.slice(screenshotPrs.length);
  remainingPoIds.forEach((poId, index) => {
    // Pick user based on modulo
    const user = users[(index + 4) % users.length];
    const deptProjects = projectSubjectsByDept[user.department] || [
      `Pengadaan Operasional Medis & Non-Medis ${user.department}`,
      `Peremajaan Inventaris & Alat Kerja ${user.department}`,
      `Kontrak Jasa & Pemeliharaan Berkala ${user.department}`
    ];
    const subject = deptProjects[index % deptProjects.length];

    const prNumber = `pr-${user.hospitalUnitCode || '0000'}-26-${String((index % 12) + 1).padStart(2, '0')}-${String(1005 + index).padStart(5, '0')}`;

    prs.push({
      id: prNumber,
      unit: user.hospitalUnitCode || '0000',
      purchaseReqId: prNumber,
      subject,
      categoryType: index % 2 === 0 ? 'contract service / repair & maintenance' : 'other opex',
      documentStatus: 'Approved',
      requester: user.username,
      costCenter: user.costCenter || '0001',
      description: user.department.toLowerCase(),
      waitingTo: '',
      erpId: poId,
      createdDate: `2026-0${(index % 6) + 1}-10`,
      submittedDate: `2026-0${(index % 6) + 1}-11`,
      totalAmount: Math.round(15000000 + (index * 8750000) % 350000000),
    });
  });

  return prs;
}
