import { HospitalMasterRecord, VendorMasterRecord } from '../../../core/types/spend';

export function generateSampleHospitalMasters(): HospitalMasterRecord[] {
  return [
    {
      id: 'hosp-1',
      hospitalCode: 'SHLV',
      erpHospitalUnitCode: '0001',
      hospitalName: 'Siloam Hospitals Lippo Village',
      city: 'Tangerang',
      region: 'Jabodetabek',
      island: 'Jawa',
      tier: 'Tier 1 - Quaternary / Center of Excellence',
      bedCapacity: 450,
      address: 'Jl. Siloam No. 6, Lippo Karawaci, Tangerang, Banten',
      isActive: true,
    },
    {
      id: 'hosp-2',
      hospitalCode: 'SHKJ',
      erpHospitalUnitCode: '0002',
      hospitalName: 'Siloam Hospitals Kebon Jeruk',
      city: 'Jakarta Barat',
      region: 'Jabodetabek',
      island: 'Jawa',
      tier: 'Tier 1 - Main Tertiary Hospital',
      bedCapacity: 280,
      address: 'Jl. Raya Perjuangan Kav. 8, Kebon Jeruk, Jakarta Barat',
      isActive: true,
    },
    {
      id: 'hosp-3',
      hospitalCode: 'MRCCC',
      erpHospitalUnitCode: '0003',
      hospitalName: 'MRCCC Siloam Hospitals Semanggi',
      city: 'Jakarta Selatan',
      region: 'Jabodetabek',
      island: 'Jawa',
      tier: 'Tier 1 - Comprehensive Cancer Center',
      bedCapacity: 320,
      address: 'Jl. Garnisun 1 No. 2-3, Semanggi, Jakarta Selatan',
      isActive: true,
    },
    {
      id: 'hosp-4',
      hospitalCode: 'SHBC',
      erpHospitalUnitCode: '0004',
      hospitalName: 'Siloam Hospitals Bekasi Timur',
      city: 'Bekasi',
      region: 'Jabodetabek',
      island: 'Jawa',
      tier: 'Tier 2 - Secondary General',
      bedCapacity: 160,
      address: 'Jl. Chairil Anwar No. 27, Bekasi Timur',
      isActive: true,
    },
    {
      id: 'hosp-5',
      hospitalCode: 'SHBG',
      erpHospitalUnitCode: '0005',
      hospitalName: 'Siloam Hospitals Bogor',
      city: 'Bogor',
      region: 'Jabodetabek',
      island: 'Jawa',
      tier: 'Tier 2 - Secondary General',
      bedCapacity: 140,
      address: 'Jl. Pajajaran No. 27, Bogor',
      isActive: true,
    },
    {
      id: 'hosp-6',
      hospitalCode: 'SHCP',
      erpHospitalUnitCode: '0006',
      hospitalName: 'Siloam Hospitals Cinere Pratama',
      city: 'Depok',
      region: 'Jabodetabek',
      island: 'Jawa',
      tier: 'Tier 3 - Community Hospital',
      bedCapacity: 90,
      address: 'Jl. Cinere Raya No. 19, Depok',
      isActive: true,
    },
    {
      id: 'hosp-7',
      hospitalCode: 'SHHO',
      erpHospitalUnitCode: '0000',
      hospitalName: 'Siloam Hospitals Head Office CGP',
      city: 'Tangerang',
      region: 'Jabodetabek',
      island: 'Jawa',
      tier: 'Corporate Central Procurement',
      bedCapacity: 0,
      address: 'Menara Matahari Lt. 15, Lippo Karawaci, Tangerang',
      isActive: true,
    },
    {
      id: 'hosp-8',
      hospitalCode: 'RSUSW',
      erpHospitalUnitCode: '0008',
      hospitalName: 'Siloam Hospitals Surabaya',
      city: 'Surabaya',
      region: 'Jawa Timur',
      island: 'Jawa',
      tier: 'Tier 1 - Regional Main Referral',
      bedCapacity: 260,
      address: 'Jl. Raya Gubeng No. 70, Surabaya, Jawa Timur',
      isActive: true,
    },
    {
      id: 'hosp-9',
      hospitalCode: 'SHAB',
      erpHospitalUnitCode: '0009',
      hospitalName: 'Siloam Hospitals Agora Bandung',
      city: 'Bandung',
      region: 'Jawa Barat',
      island: 'Jawa',
      tier: 'Tier 2 - Secondary General',
      bedCapacity: 150,
      address: 'Jl. Gandawijaya No. 12, Bandung, Jawa Barat',
      isActive: true,
    },
    {
      id: 'hosp-10',
      hospitalCode: 'SHJK',
      erpHospitalUnitCode: '0010',
      hospitalName: 'Siloam Hospitals Jember',
      city: 'Jember',
      region: 'Jawa Timur',
      island: 'Jawa',
      tier: 'Tier 2 - Secondary General',
      bedCapacity: 120,
      address: 'Jl. Gajah Mada No. 104, Jember, Jawa Timur',
      isActive: true,
    },
    {
      id: 'hosp-11',
      hospitalCode: 'SHMDN',
      erpHospitalUnitCode: '0011',
      hospitalName: 'Siloam Hospitals Dhirga Surya Medan',
      city: 'Medan',
      region: 'Sumatera Utara',
      island: 'Sumatera',
      tier: 'Tier 1 - Sumatera Referral Hub',
      bedCapacity: 240,
      address: 'Jl. Imam Bonjol No. 6, Medan, Sumatera Utara',
      isActive: true,
    },
    {
      id: 'hosp-12',
      hospitalCode: 'SHPLB',
      erpHospitalUnitCode: '0012',
      hospitalName: 'Siloam Sriwijaya Palembang',
      city: 'Palembang',
      region: 'Sumatera Selatan',
      island: 'Sumatera',
      tier: 'Tier 2 - Secondary General',
      bedCapacity: 180,
      address: 'Jl. POM IX, Palembang Square, Palembang, Sumatera Selatan',
      isActive: true,
    },
    {
      id: 'hosp-13',
      hospitalCode: 'SHBALI',
      erpHospitalUnitCode: '0013',
      hospitalName: 'Siloam Hospitals Denpasar Bali',
      city: 'Denpasar / Kuta',
      region: 'Bali',
      island: 'Bali & Nusa Tenggara',
      tier: 'Tier 1 - International & Medical Tourism',
      bedCapacity: 210,
      address: 'Jl. Sunset Road No. 818, Kuta, Bali',
      isActive: true,
    },
    {
      id: 'hosp-14',
      hospitalCode: 'SHMKS',
      erpHospitalUnitCode: '0014',
      hospitalName: 'Siloam Hospitals Makassar',
      city: 'Makassar',
      region: 'Sulawesi Selatan',
      island: 'Sulawesi',
      tier: 'Tier 1 - East Indonesia Referral Hub',
      bedCapacity: 250,
      address: 'Jl. Metro Tanjung Bunga Kav. 9, Makassar, Sulawesi Selatan',
      isActive: true,
    },
    {
      id: 'hosp-15',
      hospitalCode: 'SHBPP',
      erpHospitalUnitCode: '0015',
      hospitalName: 'Siloam Hospitals Balikpapan',
      city: 'Balikpapan',
      region: 'Kalimantan Timur (IKN Gateway)',
      island: 'Kalimantan',
      tier: 'Tier 1 - Industrial & Trauma Center',
      bedCapacity: 200,
      address: 'Jl. MT Haryono No. 23, Balikpapan, Kalimantan Timur',
      isActive: true,
    },
  ];
}

export function generateSampleVendorMasters(): VendorMasterRecord[] {
  return [
    {
      id: 'ven-1',
      vendorCode: 'VEND-001',
      vendorName: 'BHAKTI SOLUSINDO, PT',
      category: 'IT Equipment & Hardware',
      domicileCity: 'Jakarta Selatan',
      domicileRegion: 'Jabodetabek',
      domicileIsland: 'Jawa',
      npwp: '01.345.678.9-012.000',
      contactPerson: 'Bambang Sudiro',
      phone: '+62 21 5290 8800',
      email: 'sales@bhaktisolusindo.co.id',
      paymentTermDefault: 'Net 45 Days',
      tierRating: 'Tier 1 - Preferred',
      status: 'ACTIVE',
      notes: 'Principal distributor for Dell and HP enterprise laptops.',
    },
    {
      id: 'ven-2',
      vendorCode: 'VEND-002',
      vendorName: 'MEDIA KARYA UTAMA, PT',
      category: 'Office Equipment & IT Hardware',
      domicileCity: 'Jakarta Barat',
      domicileRegion: 'Jabodetabek',
      domicileIsland: 'Jawa',
      npwp: '02.112.334.5-034.000',
      contactPerson: 'Siska Handayani',
      phone: '+62 21 5698 1200',
      email: 'b2b@mediakarya.com',
      paymentTermDefault: 'Net 30 Days',
      tierRating: 'Tier 2 - Approved',
      status: 'ACTIVE',
      notes: 'Alternative IT supplier with competitive flat pricing.',
    },
    {
      id: 'ven-3',
      vendorCode: 'VEND-003',
      vendorName: 'MEDIKA SARANA SEJAHTERA',
      category: 'Medical Consumables & PPE',
      domicileCity: 'Tangerang',
      domicileRegion: 'Jabodetabek',
      domicileIsland: 'Jawa',
      npwp: '03.889.445.1-055.000',
      contactPerson: 'dr. Hendra Kurniawan',
      phone: '+62 21 5567 4300',
      email: 'tender@medikasarana.co.id',
      paymentTermDefault: 'Net 60 Days',
      tierRating: 'Tier 1 - Preferred',
      status: 'FLAGGED_PRICE_HIKE',
      notes: 'Flagged for aggressive price increase (+31%) on Surgical Gloves between Jan - May.',
    },
    {
      id: 'ven-4',
      vendorCode: 'VEND-004',
      vendorName: 'PRIMA MEDIKA UTAMA',
      category: 'Medical Consumables & Disposables',
      domicileCity: 'Surabaya',
      domicileRegion: 'Jawa Timur',
      domicileIsland: 'Jawa',
      npwp: '04.776.223.8-062.000',
      contactPerson: 'Agus Wijaya',
      phone: '+62 31 8432 9900',
      email: 'corporate@primamedika.co.id',
      paymentTermDefault: 'Net 45 Days',
      tierRating: 'Tier 1 - Preferred',
      status: 'ACTIVE',
      notes: 'Key competitor to Medika Sarana with stable long-term pricing.',
    },
    {
      id: 'ven-5',
      vendorCode: 'VEND-005',
      vendorName: 'GLOBAL PRATAMA MEDIKA',
      category: 'Medical Equipment & Biomeds',
      domicileCity: 'Jakarta Pusat',
      domicileRegion: 'Jabodetabek',
      domicileIsland: 'Jawa',
      npwp: '05.334.887.2-071.000',
      contactPerson: 'Ratna Susanti',
      phone: '+62 21 3190 2211',
      email: 'info@globalpratama.co.id',
      paymentTermDefault: 'Net 60 Days',
      tierRating: 'Tier 2 - Approved',
      status: 'ACTIVE',
      notes: 'Infusion and Syringe pump authorized technical distributor.',
    },
    {
      id: 'ven-6',
      vendorCode: 'VEND-006',
      vendorName: 'FARMA SEHAT INDONESIA',
      category: 'Pharmaceutical Reagents & Lab',
      domicileCity: 'Bandung',
      domicileRegion: 'Jawa Barat',
      domicileIsland: 'Jawa',
      npwp: '06.998.112.4-082.000',
      contactPerson: 'Rudi Hartono',
      phone: '+62 22 7300 4455',
      email: 'orders@farmasehat.co.id',
      paymentTermDefault: 'Net 30 Days',
      tierRating: 'Tier 2 - Approved',
      status: 'UNDER_REVIEW',
      notes: 'Detected selling reagent kits with high price discrepancy across RSUSW vs SHLV.',
    },
    {
      id: 'ven-7',
      vendorCode: 'VEND-007',
      vendorName: 'CITRA DIAGNOSTIKA',
      category: 'Laboratory Supplies & Reagents',
      domicileCity: 'Jakarta Barat',
      domicileRegion: 'Jabodetabek',
      domicileIsland: 'Jawa',
      npwp: '07.443.556.7-091.000',
      contactPerson: 'Dewi Lestari',
      phone: '+62 21 5489 7788',
      email: 'sales@citradiagnostika.com',
      paymentTermDefault: 'Net 45 Days',
      tierRating: 'Tier 1 - Preferred',
      status: 'ACTIVE',
      notes: 'Stable lab reagent supplier with volume discounts.',
    },
    {
      id: 'ven-8',
      vendorCode: 'VEND-008',
      vendorName: 'SUMBER ANUGRAH PLASINDO, PT',
      category: 'General Supplies & Plastics',
      domicileCity: 'Tangerang',
      domicileRegion: 'Jabodetabek',
      domicileIsland: 'Jawa',
      npwp: '08.123.998.3-019.000',
      contactPerson: 'Johan Setiawan',
      phone: '+62 21 5900 1122',
      email: 'sales@sumberanugrah.co.id',
      paymentTermDefault: 'Net 30 Days',
      tierRating: 'Tier 2 - Approved',
      status: 'ACTIVE',
      notes: 'Supplies waste bins, hygiene holders, and plastic wares.',
    },
    {
      id: 'ven-9',
      vendorCode: 'VEND-009',
      vendorName: 'DRIYATA MA LESTARI',
      category: 'General Supplies & Paperware',
      domicileCity: 'Jakarta Timur',
      domicileRegion: 'Jabodetabek',
      domicileIsland: 'Jawa',
      npwp: '09.554.123.6-028.000',
      contactPerson: 'Eko Prasetyo',
      phone: '+62 21 8611 3456',
      email: 'cs@driyata.co.id',
      paymentTermDefault: 'Net 30 Days',
      tierRating: 'Tier 3 - Under Review',
      status: 'UNDER_REVIEW',
      notes: 'Price variance observed for greeting cards and standard printing paper across regions.',
    },
    {
      id: 'ven-10',
      vendorCode: 'VEND-010',
      vendorName: 'TUV SUD Indonesia, PT',
      category: 'Professional Services & Audit',
      domicileCity: 'Jakarta Selatan',
      domicileRegion: 'Jabodetabek',
      domicileIsland: 'Jawa',
      npwp: '10.887.665.4-041.000',
      contactPerson: 'Ir. Yulianto',
      phone: '+62 21 5790 9900',
      email: 'info@tuvsud.co.id',
      paymentTermDefault: 'Net 30 Days',
      tierRating: 'Tier 1 - Preferred',
      status: 'ACTIVE',
      notes: 'Accreditation and ISO certification auditor.',
    }
  ];
}
