import { SkuMasterRecord, getFormattedSkuName } from '../../../core/types/spend';

export function generateSampleSkuRecords(): SkuMasterRecord[] {
  const raw: Omit<SkuMasterRecord, 'id' | 'formattedSkuName'>[] = [
    {
      productId: '121107092048',
      name: 'SURGICAL INSTRUMENT',
      purchCategoryLv1: 'DIAGNOSTIC AND MEDICAL DEVICES',
      purchCategoryLv2: 'SURGICAL & DIAGNOSTIC INTERVENTION SYSTEMS',
      purchCategoryLv3: 'SURGICAL',
      purchCategoryLv4: 'SURGICAL HAND INSTRUMENTS',
      prItemId: '710000019',
      prFaCategory: 'Surgical Equip',
      cprItemId: '720000021',
      cprFaCategory: 'Surgical CPR',
      spItemId: 'SP-1211',
      unitOfMeasurement: 'pcs',
      isGenericProduct: false,
      brand: 'STORZ',
      specification1: 'CLICKLINE CLAW FORCEPS INSERT, 2x3 TEETH, 10MM',
      specification2: '-',
      specification3: '-',
      partNumber: '33510FS',
      standardPrice: 1250000,
      isActive: true,
      isContract: false
    },
    {
      productId: '150603080098',
      name: 'SINGKONG',
      purchCategoryLv1: 'GENERAL SUPPLIES',
      purchCategoryLv2: 'KITCHEN SUPPLIES',
      purchCategoryLv3: 'FOOD SERVICE SUPPLIES',
      purchCategoryLv4: 'FRESH PRODUCE',
      prItemId: '710000020',
      prFaCategory: 'Dietary',
      cprItemId: '720000022',
      cprFaCategory: 'Kitchen CPR',
      spItemId: 'SP-1506',
      unitOfMeasurement: 'kg',
      isGenericProduct: true,
      brand: 'NB',
      specification1: 'STANDARD',
      specification2: '-',
      specification3: '-',
      partNumber: 'NP',
      standardPrice: 9000,
      isActive: true,
      isContract: true
    },
    {
      productId: '141020050012',
      name: 'INFUSION PUMP',
      purchCategoryLv1: 'DIAGNOSTIC AND MEDICAL DEVICES',
      purchCategoryLv2: 'ELECTROMEDICAL EQUIPMENT',
      purchCategoryLv3: 'INFUSION',
      purchCategoryLv4: 'INFUSION PUMP SINGLE',
      prItemId: '710000025',
      prFaCategory: 'Biomedical',
      cprItemId: '720000030',
      cprFaCategory: 'Med Equip CPR',
      spItemId: 'SP-1410',
      unitOfMeasurement: 'unit',
      isGenericProduct: false,
      brand: 'B.BRAUN',
      specification1: 'SPACE PLUS INFUSOMAT',
      specification2: 'PORTABLE',
      specification3: 'AC/DC',
      partNumber: '8713050',
      standardPrice: 28500000,
      isActive: true,
      isContract: true
    },
    {
      productId: '130204010045',
      name: 'DISPOSABLE SYRINGE',
      purchCategoryLv1: 'PHARMACEUTICAL & CONSUMABLES',
      purchCategoryLv2: 'MEDICAL CONSUMABLES',
      purchCategoryLv3: 'INJECTION',
      purchCategoryLv4: 'SYRINGE 10CC',
      prItemId: '710000040',
      prFaCategory: 'Consumables',
      cprItemId: '720000045',
      cprFaCategory: 'Consumables CPR',
      spItemId: 'SP-1302',
      unitOfMeasurement: 'box',
      isGenericProduct: true,
      brand: 'TERUMO',
      specification1: '10CC WITH NEEDLE 23G',
      specification2: 'STERILE',
      specification3: 'DISPOSABLE',
      partNumber: 'SS-10ES',
      standardPrice: 145000,
      isActive: true,
      isContract: true
    },
    {
      productId: '100101010140',
      name: 'PEMBANGUNAN BARU',
      purchCategoryLv1: 'GENERAL SUPPLIES',
      purchCategoryLv2: 'FACILITY & BUILDING',
      purchCategoryLv3: 'CONSTRUCTION & RENOVATION',
      purchCategoryLv4: 'BUILDING PROJECT',
      prItemId: '710000099',
      prFaCategory: 'Facility',
      cprItemId: '720000099',
      cprFaCategory: 'Facility CPR',
      spItemId: 'SP-1001',
      unitOfMeasurement: 'lot',
      isGenericProduct: true,
      brand: 'NB',
      specification1: 'STANDARD',
      specification2: '-',
      specification3: '-',
      partNumber: 'NP',
      standardPrice: 50000000,
      isActive: true,
      isContract: true
    },
    {
      productId: '110901020088',
      name: 'CT SCAN X-RAY TUBE',
      purchCategoryLv1: 'DIAGNOSTIC AND MEDICAL DEVICES',
      purchCategoryLv2: 'RADIOLOGY EQUIPMENT',
      purchCategoryLv3: 'CT SCAN',
      purchCategoryLv4: 'TUBE ASSEMBLY',
      prItemId: '710000088',
      prFaCategory: 'Radiology',
      cprItemId: '720000090',
      cprFaCategory: 'Rad CPR',
      spItemId: 'SP-1109',
      unitOfMeasurement: 'set',
      isGenericProduct: false,
      brand: 'SIEMENS',
      specification1: 'STRATON MX P',
      specification2: 'SOMATOM DEFINITION',
      specification3: 'HIGH PERFORMANCE',
      partNumber: '10492811',
      standardPrice: 450000000,
      isActive: true,
      isContract: false
    }
  ];

  return raw.map((item, index) => {
    const fullItem: SkuMasterRecord = {
      ...item,
      id: `sku-sample-${item.productId}`
    };
    fullItem.formattedSkuName = getFormattedSkuName(fullItem);
    return fullItem;
  });
}
